import generateMeasuredTemplateComponent from "./base-components/vue-measured-template.js";
import generateAttributeComponent from "./base-components/vue-attribute.js";
import generateResourceComponent from "./base-components/vue-resource.js";
import generateDocumentLinkComponent from "./base-components/vue-document-link.js";
import generateProsemirrorComponent from "./base-components/vue-prosemirror.js";
import generateRollVisualizerComponent from "./base-components/vue-roll-visualizer.js";
import generatePaperdollComponent from "./base-components/vue-paperdoll.js";
import generateCalculator from "./base-components/vue-calculator.js";
import generateTextFieldComponent from "./base-components/vue-text-field.js";
import generateDateTimeComponent from "./base-components/vue-date-time.js";
import generateTrackerComponent from "./base-components/vue-tracker.js";
import generateMacroChoiceComponent from "./base-components/vue-macro-choice.js";
import generateExtendedChoiceComponent from "./base-components/vue-extended-choice.js";
import generateDiceComponent from "./base-components/vue-dice.js";
import generateDamageApplicationComponent from "./base-components/vue-damage-application.js";
import generateDamageBonusesComponent from "./base-components/vue-damage-bonuses.js";
import generateDamageResistancesComponent from "./base-components/vue-damage-resistances.js";
import generateBooleanComponent from "./base-components/vue-boolean.js";
import generateDieComponent from "./base-components/vue-die.js";
import generateStringMethodComponent from "./base-components/vue-string.js";
import generateNumberComponent from "./base-components/vue-number.js";
import generateStringChoiceComponent from "./base-components/vue-string-choice.js";
import generateParentPropertyReferenceComponent from "./base-components/vue-parent-property-reference.js";
import generateSelfPropertyReferenceComponent from "./base-components/vue-self-property-reference.js";
import generateStringChoicesComponent from "./base-components/vue-string-choices.js";
import generateMoneyComponent from "./base-components/vue-money.js";
import generateInventoryComponent from "./base-components/vue-inventory.js";
import {Entry} from "../../../language/generated/ast.js";

export function generateBaseVueComponents(destination: string, entry?: Entry) {
    generateAttributeComponent(destination);
    generateResourceComponent(destination);
    generateDocumentLinkComponent(destination);
    generateProsemirrorComponent(destination);
    generateRollVisualizerComponent(destination);
    generatePaperdollComponent(destination);
    generateCalculator(destination);
    generateTextFieldComponent(destination);
    generateDateTimeComponent(destination);
    generateTrackerComponent(destination);
    generateMacroChoiceComponent(destination);
    generateMeasuredTemplateComponent(destination);
    generateExtendedChoiceComponent(destination);
    generateDiceComponent(destination);
    generateDamageApplicationComponent(destination);
    generateDamageBonusesComponent(destination, entry);
    generateDamageResistancesComponent(destination, entry);
    generateBooleanComponent(destination, entry);
    generateDieComponent(destination, entry);
    generateStringMethodComponent(destination, entry);
    generateNumberComponent(destination, entry);
    generateStringChoiceComponent(destination, entry);
    generateStringChoicesComponent(destination, entry);
    generateParentPropertyReferenceComponent(destination, entry);
    generateSelfPropertyReferenceComponent(destination, entry);
    generateMoneyComponent(destination, entry);
    generateInventoryComponent(destination, entry);
}
